/* eslint-disable import/prefer-default-export */

export const ROUTES = [
  {
    number: '18',
    description: 'ЦГБ - Газоаппарат',
    type: 'Автобус',
    count: 6,
    passengers: 1823,
    profit: (1823 * 0.5),
  },
  {
    number: '6',
    description: 'Городская больница №1 - Областная больница',
    type: 'Автобус',
    count: 4,
    passengers: 1659,
    profit: (1659 * 0.5),
  },
  {
    number: '37',
    description: 'ЦГБ - Брестское пиво',
    type: 'Автобус',
    count: 5,
    passengers: 2184,
    profit: (2184 * 0.5),
  },
  {
    number: '38',
    description: 'ЦГБ - Катин Бор',
    type: 'Автобус',
    count: 5,
    passengers: 2301,
    profit: (2301 * 0.5),
  },
  {
    number: '2А',
    description: 'Областная больница - Бернады',
    type: 'Автобус',
    count: 6,
    passengers: 1906,
    profit: (1906 * 0.5),
  },
  {
    number: '1',
    description: 'Областная больница-Орджоникидзе',
    type: 'Троллейбус',
    count: 5,
    passengers: 2332,
    profit: (2332 * 0.5),
  },
  {
    number: '2',
    description: 'СК Виктория -Свердлова',
    type: 'Троллейбус',
    count: 4,
    passengers: 1918,
    profit: (1918 * 0.5),
  },
  {
    number: '3',
    description: 'СК Виктория -Орджоникидзе',
    type: 'Троллейбус',
    count: 5,
    passengers: 1679,
    profit: (1679 * 0.5),
  },
  {
    number: '4',
    description: 'КСМ-Орджоникидзе',
    type: 'Троллейбус',
    count: 3,
    passengers: 1771,
    profit: (1771 * 0.5),
  },
  {
    number: '5',
    description: 'Областная больница-Цветотрон',
    type: 'Троллейбус',
    count: 3,
    passengers: 2006,
    profit: (2006 * 0.5),
  },
  {
    number: '6',
    description: 'Областная больница-Цветотрон',
    type: 'Троллейбус',
    count: 4,
    passengers: 1432,
    profit: (1432 * 0.5),
  },
  {
    number: '7',
    description: 'СК Виктория -Цветотрон',
    type: 'Троллейбус',
    count: 4,
    passengers: 2018,
    profit: (2018 * 0.5),
  },
];
